import gradio as gr
from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt

# The Function
# This function will eventually hold our Llama 3 code. 
# For now, it just takes the input and returns fake text so we can test the UI.
def extract_skills(job_description):
    
    # Fake processing time (we will delete this later)
    import time
    time.sleep(2) 
    
    fake_summary = "This is a fake summary generated by our dummy function."
    fake_skills = "* Python\n* PyTorch\n* Gradio"

    if not job_description.strip():
        job_description = "Empty"
        
    wordcloud = WordCloud(
        width=800, 
        height=400, 
        background_color='white', 
        stopwords=STOPWORDS
    ).generate(job_description)
    
    # Create a Matplotlib figure to hold the image
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.imshow(wordcloud, interpolation='bilinear')
    ax.axis("off") # Hide the ugly chart axes/gridlines
    plt.tight_layout(pad=0)
    
    # Notice we now return THREE things! because we want 3 output boxes
    return fake_summary, fake_skills, fig



# The UI (Interface)
# gr.Interface is the easiest way to build a UI. We just link our function and define the boxes.
demo = gr.Interface(
    fn=extract_skills,  # The function we defined above
    
    # The Inputs 
    inputs=gr.Textbox(
        lines=12, 
        placeholder="Paste the massive job description here...", 
        label="Job Description"
    ),
    
    # The Outputs
    # Because our function returns two strings, we need a list of two Textboxes here and gr.Plot() to catch the 'fig' we returned above!
    outputs=[
        gr.Textbox(label="AI Summary", lines=3),
        gr.Textbox(label="Required Skills", lines=6),
        gr.Plot(label="Keyword Word Cloud")
    ],
    
    # The Aesthetics
    title="🚀 Resume Skill Extractor",
    description="Paste any job description below. Our custom fine-tuned Llama 3 model will extract the core responsibilities, skills, and a keyword cloud.",
    flagging_mode="never" # Hides the default "Flag" button Gradio puts on apps
)

# Launch!
if __name__ == "__main__":
    print("Launching Gradio UI...")
    demo.launch(share=True) # share=True creates a public public web link!